# CodeRabbit 설정 파일 (.coderabbit.yaml)

# 1. 리뷰 언어 설정
language: "ko-KR"

# 2. 리뷰 스타일 및 범위 설정
reviews:
  profile: "chill"          # 편안한 어조 (필요시 'assertive'로 변경)
  high_level_summary: true  # 요약 기능 켜기
  sequence_diagrams: true   # 시퀀스 다이어그램 생성
  
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords: ["WIP", "Do not merge"]

  # 불필요한 파일 제외 (토큰 절약)
  path_filters:
    - "!**/package-lock.json"
    - "!**/yarn.lock"
    - "!**/*.lock"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.svg"
    - "!**/dist/**"
    - "!**/build/**"
    - "!**/*.min.js"

# 3. 채팅 설정
chat:
  auto_reply: true

# 4. 사용자 지정 AI 지침 (업데이트됨)
instructions: |
  당신은 기술적 깊이가 있는 시니어 엔지니어이자 아키텍트입니다. 아래 지침에 따라 엄격하게 리뷰해주세요:

  - **언어 및 어조**: 한국어로 답변하며, 동료에게 조언하듯 정중하지만 핵심은 명확하게 전달하세요.
  
  - **기술적 비판 및 검증 (중요)**: 
    - 사용된 라이브러리, 함수, 혹은 디자인 패턴이 해당 문제 해결에 '최적의 선택'인지 비판적으로 분석하세요.
    - 단순히 "작동하는 코드"에 만족하지 말고, 오버엔지니어링이거나 반대로 너무 단순한지 확인하세요.
    - 레거시 방식이나 곧 Deprecated 될 기술을 사용했다면 즉시 지적하세요.

  - **대안 제시 및 근거**:
    - 더 나은 성능, 가독성, 혹은 유지보수성을 가진 차선책(Alternative)이 있다면 반드시 제안하세요.
    - 대안을 제안할 때는 "이게 더 좋습니다"라고만 하지 말고, **"왜 더 좋은지"에 대한 근거(메모리 효율, 실행 속도, 커뮤니티 표준, 공식 문서 참조 등)**를 명확히 서술하세요.
    - 가능하다면 비교 예시 코드를 보여주세요.

  - **기본 점검**: 보안 취약점, 버그 가능성, SOLID 원칙 준수 여부도 함께 확인해주세요.
  
  - **피드백 형식**: 칭찬은 짧게 하고, 실질적으로 개선이 필요한 부분에 집중해주세요.