services:
  backend:
    restart: always
    environment:
      - DEBUG=True
    networks:
      - todac-network
      - npm_network
  grafana:
    environment:
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-grafana.todac.cloud}
      - GF_SERVER_ROOT_URL=https://${GRAFANA_DOMAIN:-grafana.todac.cloud}
    networks:
      - todac-network
      - npm_network
  attu:
    networks:
      - npm_network
networks:
  npm_network:
    external: true

